### ISSUE TITLE
mac 下源码文件名带"-"时报错

### ISSUE THREAD

**Issue by nobodxbodon** [fanx-dev/fanx#3]
估计 Linux 下也会
```
./fan hello-ui.fan 
CompilerInput: Pod name contains invalid char '-'
java.lang.NullPointerException
	at fan.compiler.Compiler.cleanup(Compiler.fan:131)
	at fan.compiler.Compiler.compile(Compiler.fan:74)
	at fan.compiler.Main.compileScript(Main.fan:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fan.std.Method.invoke(Method.java:422)
	at fan.std.Method$MethodFunc.callWith(Method.java:310)
	at fan.std.Method$MethodFunc.call(Method.java:234)
	at fan.std.Method.call(Method.java:164)
	at fan.std.ScriptCompiler.compileFile(ScriptCompiler.fan:52)
	at fan.std.ScriptCompiler.execute(ScriptCompiler.fan:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fanx.util.Reflection.callMethodThrow(Reflection.java:155)
	at fanx.tools.Fan.executeFile(Fan.java:109)
	at fanx.tools.Fan.execute(Fan.java:48)
	at fanx.tools.Fan.run(Fan.java:356)
	at fanx.tools.Fan.main(Fan.java:394)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fanx.util.Reflection.callMethodThrow(Reflection.java:155)
	at fanx.tools.Fan.executeFile(Fan.java:109)
	at fanx.tools.Fan.execute(Fan.java:48)
	at fanx.tools.Fan.run(Fan.java:356)
	at fanx.tools.Fan.main(Fan.java:394)
Caused by: compiler::CompilerErr: Pod name contains invalid char '-'
	at fan.compiler.CompilerErr.make(CompilerErr.fan:15)
	at fan.compiler.CompilerSupport.err(CompilerSupport.fan:102)
	at fan.compiler.InitInput$validatePodName$0.doCall(InitInput.fan:81)
	at fan.compiler.InitInput$validatePodName$0.call(InitInput.fan:79)
	at fan.sys.FanStr.each(FanStr.java:372)
	at fan.compiler.InitInput.validatePodName(InitInput.fan:79)
	at fan.compiler.InitInput.run(InitInput.fan:44)
	at fan.compiler.Compiler.frontend(Compiler.fan:85)
	at fan.compiler.Compiler.compile(Compiler.fan:66)
	at fan.compiler.Main.compileScript(Main.fan:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fan.std.Method.invoke(Method.java:422)
	at fan.std.Method$MethodFunc.callWith(Method.java:310)
	at fan.std.Method$MethodFunc.call(Method.java:234)
	at fan.std.Method.call(Method.java:164)
	at fan.std.ScriptCompiler.compileFile(ScriptCompiler.fan:52)
	at fan.std.ScriptCompiler.execute(ScriptCompiler.fan:64)
	... 9 more
```

**Comment by chunquedong** [comment]
'-'还有减法的意思，不能作为标识符，你用下划线吧。

**Comment by nobodxbodon** [comment]
不是标识符，是源文件的文件名。[这里](https://zhuanlan.zhihu.com/p/62786295)的`HelloGui.fan`命名成了`hello-ui.fan`。

**Comment by chunquedong** [comment]
内部有个包名，类似于命名空间，默认是按照文件名来的。

**Comment by chunquedong** [comment]
fixed
